mysql:
  image: mysql:5.7.14
  volumes:
    - ./mysql/conf:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: password
redmine:
  image: sameersbn/redmine:3.2.4
  links:
    - mysql:mysql
  environment:
    DB_NAME: redmine
    DB_USER: root
    DB_PASS: password
    REDMINE_PORT: 10083
    DB_ENCODING: utf8mb4
  volumes:
    - ../:/home/redmine/data/plugins/redmine_chatwork
    - ./log:/home/redmine/redmine/log
  ports:
    - "10083:80"
